//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/dev/KScr/grammar\KScrParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace KScr.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="KScrParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IKScrParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.packageDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageDecl([NotNull] KScrParser.PackageDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.imports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImports([NotNull] KScrParser.ImportsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.importDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportDecl([NotNull] KScrParser.ImportDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.annotationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationArg([NotNull] KScrParser.AnnotationArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] KScrParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modPublic</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModPublic([NotNull] KScrParser.ModPublicContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modInternal</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModInternal([NotNull] KScrParser.ModInternalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modProtected</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModProtected([NotNull] KScrParser.ModProtectedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modPrivate</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModPrivate([NotNull] KScrParser.ModPrivateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modStatic</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModStatic([NotNull] KScrParser.ModStaticContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modFinal</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModFinal([NotNull] KScrParser.ModFinalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modAbstract</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModAbstract([NotNull] KScrParser.ModAbstractContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modSyncronized</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModSyncronized([NotNull] KScrParser.ModSyncronizedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modNative</c>
	/// labeled alternative in <see cref="KScrParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModNative([NotNull] KScrParser.ModNativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifiers([NotNull] KScrParser.ModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ctClass</c>
	/// labeled alternative in <see cref="KScrParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtClass([NotNull] KScrParser.CtClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ctInterface</c>
	/// labeled alternative in <see cref="KScrParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtInterface([NotNull] KScrParser.CtInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ctEnum</c>
	/// labeled alternative in <see cref="KScrParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtEnum([NotNull] KScrParser.CtEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ctAnnotation</c>
	/// labeled alternative in <see cref="KScrParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtAnnotation([NotNull] KScrParser.CtAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.genericTypeUses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericTypeUses([NotNull] KScrParser.GenericTypeUsesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>importedTypeName</c>
	/// labeled alternative in <see cref="KScrParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportedTypeName([NotNull] KScrParser.ImportedTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>normalTypeUse</c>
	/// labeled alternative in <see cref="KScrParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalTypeUse([NotNull] KScrParser.NormalTypeUseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrayTypeUse</c>
	/// labeled alternative in <see cref="KScrParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayTypeUse([NotNull] KScrParser.ArrayTypeUseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.rawType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRawType([NotNull] KScrParser.RawTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.genericTypeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericTypeDef([NotNull] KScrParser.GenericTypeDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.genericTypeDefs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericTypeDefs([NotNull] KScrParser.GenericTypeDefsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.objectExtends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectExtends([NotNull] KScrParser.ObjectExtendsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.objectImplements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectImplements([NotNull] KScrParser.ObjectImplementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] KScrParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] KScrParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] KScrParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] KScrParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.noBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoBlock([NotNull] KScrParser.NoBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.uniformBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUniformBlock([NotNull] KScrParser.UniformBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.normalBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalBlock([NotNull] KScrParser.NormalBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.memberExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberExpr([NotNull] KScrParser.MemberExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.lambdaBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaBlock([NotNull] KScrParser.LambdaBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseStmtBlock</c>
	/// labeled alternative in <see cref="KScrParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseStmtBlock([NotNull] KScrParser.CaseStmtBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseExprBlock</c>
	/// labeled alternative in <see cref="KScrParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseExprBlock([NotNull] KScrParser.CaseExprBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberNormalBlock</c>
	/// labeled alternative in <see cref="KScrParser.memberBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberNormalBlock([NotNull] KScrParser.MemberNormalBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberExprBlock</c>
	/// labeled alternative in <see cref="KScrParser.memberBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberExprBlock([NotNull] KScrParser.MemberExprBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberNoBlock</c>
	/// labeled alternative in <see cref="KScrParser.memberBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberNoBlock([NotNull] KScrParser.MemberNoBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>codeNormalBlock</c>
	/// labeled alternative in <see cref="KScrParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeNormalBlock([NotNull] KScrParser.CodeNormalBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>codeStmtBlock</c>
	/// labeled alternative in <see cref="KScrParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeStmtBlock([NotNull] KScrParser.CodeStmtBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>codeNoBlock</c>
	/// labeled alternative in <see cref="KScrParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeNoBlock([NotNull] KScrParser.CodeNoBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.initDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDecl([NotNull] KScrParser.InitDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.subConstructorCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubConstructorCall([NotNull] KScrParser.SubConstructorCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.subConstructorCalls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubConstructorCalls([NotNull] KScrParser.SubConstructorCallsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.constructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDecl([NotNull] KScrParser.ConstructorDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDecl([NotNull] KScrParser.MethodDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.indexerMemberDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexerMemberDecl([NotNull] KScrParser.IndexerMemberDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.propGetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropGetter([NotNull] KScrParser.PropGetterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.propSetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropSetter([NotNull] KScrParser.PropSetterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.propInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropInit([NotNull] KScrParser.PropInitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>propComputed</c>
	/// labeled alternative in <see cref="KScrParser.propBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropComputed([NotNull] KScrParser.PropComputedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>propAccessors</c>
	/// labeled alternative in <see cref="KScrParser.propBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropAccessors([NotNull] KScrParser.PropAccessorsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>propFieldStyle</c>
	/// labeled alternative in <see cref="KScrParser.propBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropFieldStyle([NotNull] KScrParser.PropFieldStyleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.propertyDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDecl([NotNull] KScrParser.PropertyDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memProp</c>
	/// labeled alternative in <see cref="KScrParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemProp([NotNull] KScrParser.MemPropContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memCls</c>
	/// labeled alternative in <see cref="KScrParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemCls([NotNull] KScrParser.MemClsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memInit</c>
	/// labeled alternative in <see cref="KScrParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemInit([NotNull] KScrParser.MemInitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memCtor</c>
	/// labeled alternative in <see cref="KScrParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemCtor([NotNull] KScrParser.MemCtorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memMtd</c>
	/// labeled alternative in <see cref="KScrParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemMtd([NotNull] KScrParser.MemMtdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memIdx</c>
	/// labeled alternative in <see cref="KScrParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemIdx([NotNull] KScrParser.MemIdxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDecl([NotNull] KScrParser.ClassDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] KScrParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.inferType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInferType([NotNull] KScrParser.InferTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.indexerEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexerEmpty([NotNull] KScrParser.IndexerEmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.indexerDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexerDecl([NotNull] KScrParser.IndexerDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.indexerExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexerExpr([NotNull] KScrParser.IndexerExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.cast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast([NotNull] KScrParser.CastContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] KScrParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.mutation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMutation([NotNull] KScrParser.MutationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] KScrParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.ctorCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtorCall([NotNull] KScrParser.CtorCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.newArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewArray([NotNull] KScrParser.NewArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.newListedArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewListedArray([NotNull] KScrParser.NewListedArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] KScrParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>methodRef</c>
	/// labeled alternative in <see cref="KScrParser.lambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodRef([NotNull] KScrParser.MethodRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lambdaExpr</c>
	/// labeled alternative in <see cref="KScrParser.lambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpr([NotNull] KScrParser.LambdaExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] KScrParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.throwStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowStatement([NotNull] KScrParser.ThrowStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.markStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMarkStatement([NotNull] KScrParser.MarkStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] KScrParser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.tryCatchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryCatchStatement([NotNull] KScrParser.TryCatchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.tryWithResourcesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryWithResourcesStatement([NotNull] KScrParser.TryWithResourcesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.catchBlocks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchBlocks([NotNull] KScrParser.CatchBlocksContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.catchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchBlock([NotNull] KScrParser.CatchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.finallyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinallyBlock([NotNull] KScrParser.FinallyBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] KScrParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] KScrParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] KScrParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] KScrParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.foreachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachStatement([NotNull] KScrParser.ForeachStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.doWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhile([NotNull] KScrParser.DoWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] KScrParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.caseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseClause([NotNull] KScrParser.CaseClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.defaultClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultClause([NotNull] KScrParser.DefaultClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtDeclare</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtDeclare([NotNull] KScrParser.StmtDeclareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtAssign</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtAssign([NotNull] KScrParser.StmtAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtAssignTuple</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtAssignTuple([NotNull] KScrParser.StmtAssignTupleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtCallMember</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtCallMember([NotNull] KScrParser.StmtCallMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtReturn</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtReturn([NotNull] KScrParser.StmtReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtThrow</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtThrow([NotNull] KScrParser.StmtThrowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtMark</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtMark([NotNull] KScrParser.StmtMarkContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtJump</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtJump([NotNull] KScrParser.StmtJumpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtTryCatch</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtTryCatch([NotNull] KScrParser.StmtTryCatchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtTryWithRes</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtTryWithRes([NotNull] KScrParser.StmtTryWithResContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtIf</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtIf([NotNull] KScrParser.StmtIfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtWhile</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtWhile([NotNull] KScrParser.StmtWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtDoWhile</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtDoWhile([NotNull] KScrParser.StmtDoWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtFor</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtFor([NotNull] KScrParser.StmtForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtForeach</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtForeach([NotNull] KScrParser.StmtForeachContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtSwitch</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtSwitch([NotNull] KScrParser.StmtSwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtPipeListen</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtPipeListen([NotNull] KScrParser.StmtPipeListenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtPipeRead</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtPipeRead([NotNull] KScrParser.StmtPipeReadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtPipeWrite</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtPipeWrite([NotNull] KScrParser.StmtPipeWriteContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtEmpty</c>
	/// labeled alternative in <see cref="KScrParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtEmpty([NotNull] KScrParser.StmtEmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.typedExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedExpr([NotNull] KScrParser.TypedExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parens</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] KScrParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opPostfix</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpPostfix([NotNull] KScrParser.OpPostfixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprCallMember</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprCallMember([NotNull] KScrParser.ExprCallMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opPrefix</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpPrefix([NotNull] KScrParser.OpPrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>readIndexer</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadIndexer([NotNull] KScrParser.ReadIndexerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>newListedArrayValue</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewListedArrayValue([NotNull] KScrParser.NewListedArrayValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprLambda</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprLambda([NotNull] KScrParser.ExprLambdaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>checkInstanceof</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCheckInstanceof([NotNull] KScrParser.CheckInstanceofContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprCast</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprCast([NotNull] KScrParser.ExprCastContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>yieldExpr</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYieldExpr([NotNull] KScrParser.YieldExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rangeInvoc</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeInvoc([NotNull] KScrParser.RangeInvocContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opBinaryLate</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpBinaryLate([NotNull] KScrParser.OpBinaryLateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nativeLitValue</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeLitValue([NotNull] KScrParser.NativeLitValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprPipeListen</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprPipeListen([NotNull] KScrParser.ExprPipeListenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprThrow</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprThrow([NotNull] KScrParser.ExprThrowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varAssign</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarAssign([NotNull] KScrParser.VarAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>newArrayValue</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewArrayValue([NotNull] KScrParser.NewArrayValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprSwitch</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprSwitch([NotNull] KScrParser.ExprSwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varValue</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarValue([NotNull] KScrParser.VarValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opBinary</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpBinary([NotNull] KScrParser.OpBinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varDeclare</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclare([NotNull] KScrParser.VarDeclareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprTuple</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprTuple([NotNull] KScrParser.ExprTupleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeValue</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeValue([NotNull] KScrParser.TypeValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>callCtor</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallCtor([NotNull] KScrParser.CallCtorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ternary</c>
	/// labeled alternative in <see cref="KScrParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTernary([NotNull] KScrParser.TernaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.tupleDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleDeclType([NotNull] KScrParser.TupleDeclTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.tupleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleDecl([NotNull] KScrParser.TupleDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.tupleExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleExpr([NotNull] KScrParser.TupleExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opMultiply</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpMultiply([NotNull] KScrParser.OpMultiplyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opDivide</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpDivide([NotNull] KScrParser.OpDivideContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opModulus</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpModulus([NotNull] KScrParser.OpModulusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opBitAnd</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpBitAnd([NotNull] KScrParser.OpBitAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opBitOr</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpBitOr([NotNull] KScrParser.OpBitOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opBitNot</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpBitNot([NotNull] KScrParser.OpBitNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opLogicAnd</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLogicAnd([NotNull] KScrParser.OpLogicAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opLogicOr</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLogicOr([NotNull] KScrParser.OpLogicOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opPow</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpPow([NotNull] KScrParser.OpPowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opEqual</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpEqual([NotNull] KScrParser.OpEqualContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opInequal</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpInequal([NotNull] KScrParser.OpInequalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opGreaterEq</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpGreaterEq([NotNull] KScrParser.OpGreaterEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opLesserEq</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLesserEq([NotNull] KScrParser.OpLesserEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opGreater</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpGreater([NotNull] KScrParser.OpGreaterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opLesser</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLesser([NotNull] KScrParser.OpLesserContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opLShift</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLShift([NotNull] KScrParser.OpLShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opRShift</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpRShift([NotNull] KScrParser.OpRShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opULShift</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpULShift([NotNull] KScrParser.OpULShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opURShift</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpURShift([NotNull] KScrParser.OpURShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opNullFallback</c>
	/// labeled alternative in <see cref="KScrParser.binaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpNullFallback([NotNull] KScrParser.OpNullFallbackContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opPlus</c>
	/// labeled alternative in <see cref="KScrParser.binaryop_late"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpPlus([NotNull] KScrParser.OpPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opMinus</c>
	/// labeled alternative in <see cref="KScrParser.binaryop_late"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpMinus([NotNull] KScrParser.OpMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opArithNot</c>
	/// labeled alternative in <see cref="KScrParser.prefixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpArithNot([NotNull] KScrParser.OpArithNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opLogicNot</c>
	/// labeled alternative in <see cref="KScrParser.prefixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLogicNot([NotNull] KScrParser.OpLogicNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opIncrRead</c>
	/// labeled alternative in <see cref="KScrParser.prefixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpIncrRead([NotNull] KScrParser.OpIncrReadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opDecrRead</c>
	/// labeled alternative in <see cref="KScrParser.prefixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpDecrRead([NotNull] KScrParser.OpDecrReadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opReadIncr</c>
	/// labeled alternative in <see cref="KScrParser.postfixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpReadIncr([NotNull] KScrParser.OpReadIncrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opReadDecr</c>
	/// labeled alternative in <see cref="KScrParser.postfixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpReadDecr([NotNull] KScrParser.OpReadDecrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] KScrParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.idPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdPart([NotNull] KScrParser.IdPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] KScrParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KScrParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple([NotNull] KScrParser.TupleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numTypeLitTuple</c>
	/// labeled alternative in <see cref="KScrParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumTypeLitTuple([NotNull] KScrParser.NumTypeLitTupleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numTypeLitByte</c>
	/// labeled alternative in <see cref="KScrParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumTypeLitByte([NotNull] KScrParser.NumTypeLitByteContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numTypeLitShort</c>
	/// labeled alternative in <see cref="KScrParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumTypeLitShort([NotNull] KScrParser.NumTypeLitShortContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numTypeLitInt</c>
	/// labeled alternative in <see cref="KScrParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumTypeLitInt([NotNull] KScrParser.NumTypeLitIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numTypeLitLong</c>
	/// labeled alternative in <see cref="KScrParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumTypeLitLong([NotNull] KScrParser.NumTypeLitLongContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numTypeLitFloat</c>
	/// labeled alternative in <see cref="KScrParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumTypeLitFloat([NotNull] KScrParser.NumTypeLitFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numTypeLitDouble</c>
	/// labeled alternative in <see cref="KScrParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumTypeLitDouble([NotNull] KScrParser.NumTypeLitDoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeLitObject</c>
	/// labeled alternative in <see cref="KScrParser.primitiveTypeLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLitObject([NotNull] KScrParser.TypeLitObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeLitArray</c>
	/// labeled alternative in <see cref="KScrParser.primitiveTypeLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLitArray([NotNull] KScrParser.TypeLitArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeLitTuple</c>
	/// labeled alternative in <see cref="KScrParser.primitiveTypeLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLitTuple([NotNull] KScrParser.TypeLitTupleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeLitNum</c>
	/// labeled alternative in <see cref="KScrParser.primitiveTypeLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLitNum([NotNull] KScrParser.TypeLitNumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeLitType</c>
	/// labeled alternative in <see cref="KScrParser.primitiveTypeLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLitType([NotNull] KScrParser.TypeLitTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeLitEnum</c>
	/// labeled alternative in <see cref="KScrParser.primitiveTypeLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLitEnum([NotNull] KScrParser.TypeLitEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeLitVoid</c>
	/// labeled alternative in <see cref="KScrParser.primitiveTypeLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLitVoid([NotNull] KScrParser.TypeLitVoidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varThis</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarThis([NotNull] KScrParser.VarThisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varSuper</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarSuper([NotNull] KScrParser.VarSuperContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varLitNum</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLitNum([NotNull] KScrParser.VarLitNumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varLitTrue</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLitTrue([NotNull] KScrParser.VarLitTrueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varLitFalse</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLitFalse([NotNull] KScrParser.VarLitFalseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varLitStr</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLitStr([NotNull] KScrParser.VarLitStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varLitStdio</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLitStdio([NotNull] KScrParser.VarLitStdioContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varLitEndl</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLitEndl([NotNull] KScrParser.VarLitEndlContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varLitNull</c>
	/// labeled alternative in <see cref="KScrParser.primitiveLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLitNull([NotNull] KScrParser.VarLitNullContext context);
}
} // namespace KScr.Antlr
